management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
spring:
  application:
    name: hello-service
  cloud:
    kubernetes:
      reload:
        enabled: false
        mode: polling
        period: 5000
      config:
        sources:
          - name: ${spring.application.name}
          - name: common-config