---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "hello-service"
  version: "1"
spec:
  replicas: 2
  selector:
    app: "hello-service"
  strategy:
    rollingParams:
      timeoutSeconds: 1080
    type: "Rolling"
  template:
    metadata:
      labels:
        group: 'demo'
        app: "hello-service"
    spec:
      containers:
      - image: "172.30.1.1:5000/myproject/hello-service:latest"
        imagePullPolicy: "Always"
        name: "hello-service-4"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        securityContext:
          privileged: false
        command: ["/bin/sh", "-c"]
        args: ["cd /app; java -jar hello-service.jar"]
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector:14267"
  triggers:
  - type: "ConfigChange"
