apiVersion: v1
kind: Service
metadata:
  name: ip-service
  labels:
    app: ip-service
spec:
  ports:
  - port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: ip-service
  type: "LoadBalancer"